package com.example.smartcity.model;

import org.springframework.data.annotation.Id;
import java.time.LocalDateTime;

public class Message {
    @Id
    public String id;  // Auto-generated by Mongo
    public String senderId;  // User ID of sender
    public String senderRole;  // "OWNER" or "ADMIN"
    public String content;  // Message text
    public LocalDateTime timestamp = LocalDateTime.now();
}