// src/main/java/com/example/smartcity/model/Notification.java
package com.example.smartcity.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document(collection = "notifications")
public class Notification {

    @Id
    public String id;  // Auto-generated by MongoDB

    public String userId;  // ID of the recipient (Citizen, Owner, or Admin). Can be null for broadcast/area notifications

    public NotificationType type;  // Type of notification (enum for type-safety)

    public String title;  // Short title, e.g., "Request Approved!"

    public String message;  // Detailed message or preview

    public String relatedId;  // ID of the related entity, e.g., requestId or conversationId

    public String relatedType;  // Type of related entity, e.g., "ServiceRequest" or "Conversation"

    public boolean isRead = false;  // Default to unread

    public LocalDateTime createdAt = LocalDateTime.now();  // Timestamp of creation

    public String municipality;  // Optional: For rough area filtering (e.g., citizen notifications)

    public Double lat;  // NEW: Latitude of the business (set for NEW_BUSINESS_APPROVED)

    public Double lng;  // NEW: Longitude of the business (set for NEW_BUSINESS_APPROVED)

    // Enum for notification types – extend as needed
    public enum NotificationType {
        REQUEST_STATUS_CHANGED,  // e.g., Pending → Approved/Rejected (personal to owner)
        NEW_MESSAGE,             // New chat message
        DOCUMENT_REQUESTED,      // Admin asks for more docs
        NEW_BUSINESS_APPROVED,   // For citizens: New shop/service in your area (broadcast)
        REVIEW_ADDED             // Optional: Someone reviewed your business
    }
}